### ISSUE TITLE
Installation prompts for .NET 2.5

### ISSUE THREAD

**Issue by MoltenArrow** [beyondcomputing-org/NewRelic.HyperV#1]
Installing the plugin on a 2012 R2 server prompts for .NET 25/3.0 install and fails. Req's say .NET 4.5.2 or 4.6.  Am I missing something?
![image](https://cloud.githubusercontent.com/assets/23122736/19810299/ea0fc1ce-9cfa-11e6-9c94-3edea23225d2.png)

**Comment by eelkram** [comment]
Thanks for the info, let me take a look and i'll report back.

**Comment by eelkram** [comment]
After doing some more investigation the requirement for .Net 2 / 3.5 is from the New Relic's NPI platform.  The wrapper that they use to turn the console application into a service requires the older .Net version.  I confirmed the plugin can run independent of NPI without .Net 2 / 3.5.  If you do not want to use NPI or .Net 2 / 3.5 you can run the plugin.exe directly.  To run as a background task you can either use another wrapper to convert the app to a service or create a scheduled task to run plugin.exe on startup.

If it would be useful I might consider adding a .net service directly to the plugin that can be installed outside of NPI.  I also created a new discussion on their forum to see if we get any feedback (https://discuss.newrelic.com/t/npi-net-2-3-5-requirement/42908).
