### ISSUE TITLE
Seems to be broken on Windows Server 2016

### ISSUE THREAD

**Issue by nosovk** [beyondcomputing-org/NewRelic.HyperV#2]
When I try to install it to newly deployed Windows Server 2016 it starts, but fails to fetch information from HyperV server
[screenshot](http://take.ms/0eCRY)

**Comment by eelkram** [comment]
I'll take a look this afternoon.  Are you running the plugin on the Hyper-V server or on a remote server?

**Comment by nosovk** [comment]
I'm running it locally on Hyperv server

**Comment by eelkram** [comment]
Thanks.  Also, are you running it under an administrator account in an elevated (Run As Administrator) cmd prompt?

**Comment by eelkram** [comment]
I validated the plugin works on a stock Server 2016 installation if run from an elevated cmd prompt.  If you run from a non-elevated cmd prompt you will see the issue in your screenshot.  I'll update the application to handle this automatically so this won't be a problem in the future.

**Comment by eelkram** [comment]
Addressed in PR #3
